environment:
  ELECTRON_NO_ATTACH_CONSOLE: 1
  VSCODE_BUILD_VERBOSE: true

# platform:
#   - x86
#   - x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\Yarn\cache'
  - '%APPDATA%\npm-cache'

artifacts:
  - path: svn-scm.vsix
    name: SVN-SCM

install:
  - ps: Install-Product node 8.9.1
  - npm install -g npm vsce
  - node --version
  - npm --version
  - npm install

build_script:
  - vsce package -o svn-scm.vsix
  # For coverage
  - ps: (get-content package.json) | %{$_ -replace '"\*"',''} | set-content package.json


test_script:
  - npm test --silent

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh
